source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'


target 'HISwiftExtensions_Tests' do
    pod "HISwiftExtensions", :path => "../"

    pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'swift-3.0'
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
