source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'
swift_version = '3.0'


target 'HISwiftExtensions_Tests' do
    pod "HISwiftExtensions", :path => "../"

    pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'swift-3.0'
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
end

